- README.md
Missed that one in last pull request.
> Java version requriement removed from README.md

- Antlr/Comments.cs
- Asn1f2/Program.cs
- Asn1f2/SvnVersion.cs
- Ast/Acn.fs
- Ast/AcnCreateFromAntlr.fs
- Ast/AcnTypes.fs
- Ast/Ast.fs
- Ast/UpdateAcnProperties.fs
- README.md
Bug #425
ACN comments added to SEQUENCE and CHOICE fields are now available to ICD backends
> Comments in acn

- Ast/Ast.fs
- Ast/CloneTree.fs
- Ast/CreateAsn1AstFromAntlrTree.fs
- Ast/MapParamAstToNonParamAst.fs
- Ast/ParameterizedAsn1Ast.fs
- Backend2.ST/icd_acn.stg
- Backend2/icdAcn.fs
- Backend2/spark_utils.fs
* most of colors etc. moved to CSS section of generated HTML
* HTML tables columns aligned
* Text in table cells left aligned
> icdAcn: general cleanup

- Backend2.ST/icd_acn.stg
isAnonymousType -> bIsAnonymousType
> icdAcn: var in stg renamed to match proper notation

- asn1crt/asn1crt.c
Address Sanitizer detected buffer-overflow
> fixed unchecked read by C runtime

- Backend2.ST/icd_acn.stg
It's useful when embedding generated HTML document inside another document with page margins etc.
> Generated ICD ACN made more condensed

- asn1crt/Acn.c
- asn1crt/asn1crt.c
my last pull-req was missing one last change, this one is fixing it
> asn1crt: some private functions unfortunatelly can't be static

- Ast/Acn.fs
- Backend.c/c_uper.fs
- Backend.c/c_validate.fs
- Backend2/spark_uper.fs
- Backend2/spark_validate.fs
Seq.nth was deprecated in F# 4.0
> Replace Seq.nth with Seq.item

- Asn1f2/Program.cs
I will need to add a **ParseSDLInputFiles** eventually, and would rather not copy paste 25 lines.
> Refactor parse functions

- contrib/cdt/asn1crt/.cproject
- contrib/cdt/asn1crt/.gitignore
- contrib/cdt/asn1crt/.project
- contrib/cdt/asn1crt/.settings/language.settings.xml
add asn1crt eclipse/CDT project configuration as external contribution
cf #67
> add CDT project for asn1crt

- Backend2.ST/icd_acn.stg
Some tools (MS Word) do not recognize 'grey' as defined color...
> ACN ICD - changed 'grey' to 'gray' in .css file

- Asn1.sln
- Backend.c.ST/Backend.c.ST.fsproj
- Backend2.ST/Backend2.ST.fsproj
- StgAda/StgAda.fsproj
- StgC/StgC.fsproj
- StgVarious/StgVarious.fsproj
- appveyor.yml
see appveyor log: https://ci.appveyor.com/project/hcorg/asn1scc/build/3.3.20.5
currently it only builds, running tests requires some more refactoring
I've also fixed some dependencies between projects (removed dependecies definitions from sln file), so it builds using Microsoft's msbuild.
> AppVeyor configuration added

- Dockerfile
> nuget added to Dockerfile

- AntlrUtils/AntlrUtils.fsproj
- Ast/Ast.fsproj
- Backend.c.ST/Backend.c.ST.fsproj
- Backend.c/Backend.c.fsproj
- Backend2.ST/Backend2.ST.fsproj
- Backend2/Backend2.fsproj
- BackendAst/BackendAst.fsproj
- ST/ST.fsproj
- StgAda/StgAda.fsproj
- StgC/StgC.fsproj
- StgVarious/StgVarious.fsproj
https://bugzilla.xamarin.com/show_bug.cgi?id=60467
> Fix for FSC internal error appearing on Travis

- BackendAst/DAstExportToXml.fs
- FrontEndAst/ExportToXml.fs
> [V4] XML attributes naming convention made consistent

- FrontEndAst/Asn1AcnAstUtilFunctions.fs
- FrontEndAst/ExportToXml.fs
> [V4] *Variables -> *Values in XML AST (more consistent)

- asn1crt/asn1crt.c
- asn1crt/asn1crt.h
- asn1crt/asn1crt_encoding.c
- asn1crt/asn1crt_encoding.h
- asn1crt/asn1crt_encoding_uper.c
A few minor tweaks and cleanups that allow the generated code to be compiled with g++ and a lot more warnings enabled.
> gitPrototype fixup

- asn1crt/asn1crt.h
Instead of trying to figure out "int" size, lets rely on what C provides.
It's quite important in 16bit environments (microcontrollers)
> asn1crt.h - support for C99 stdint.h added

- Daemon.ExampleClient/Client.py
- Daemon/Asn1ServiceBindings.fs
- Daemon/Daemon.fsproj
- Daemon/Http.fs
- Daemon/packages.config
- Service.Implementation/Asn1Service.fs
- Service/Dto.fs
- Service/IAsn1Service.fs
- Service/Service.fsproj
resubmitting  #158 from new repository
>  Passing generation options in daemon

- contrib/cmake/FindAsn1scc.cmake
- contrib/cmake/README.md
As discussed in my other issue, this adds a CMake module allowing people to use asn1scc in CMake projects.
> Add Asn1scc cmake module

- Dockerfile
Fix the Dockerfile to build on Debian buster and only take fsharp from Debian Stretch (since it was removed from buster)
> Feature buster

- asn1scc/Program.fs
Upgrade to 4.6.0.0 as the new feature to reduce the amount of generated code is major
> Update version in Program.fs
