- Antlr/Comments.cs
- Ast/CreateAsn1AstFromAntlrTree.fs
- Backend2/icdAcn.fs
- Backend2/icdUper.fs
Fixed various issues related to ICD generation:
- inline comments used in SEQUENCE and CHOICE fields were not properly parsed and therefore did not appear in the right column of the ICDs
- UPER ICDs has few issues with the handling of SIZE constraint in SEQUENCE OF
> Fixing icd generator

- Ast/CreateAsn1AstFromAntlrTree.fs
For code:
Some-Type ::= ENUMERATED
{
item(1) -- Comment XYZ
}
"Comment XYZ" was not properly gathered for 'item' and as a result did not appear in generated ICD
> ICD: fixed comments for enumerated items

- Backend.c.ST/c_aux.stg
- asn1crt/asn1crt.c
Clang was detecting "self assign" and "missing newline at end of file"
warnings
> removed some warnings in generated C code (detected by clang)

- asn1crt/asn1crt.h
also fixed - warning generated by SWIG when used with DMT tools
> asn1crt: stdbool.h is present in newer versions of MSVC

- asn1crt/asn1crt.h
> asn1crt: new versions of MSVC define INFINITY & NAN macros

- contrib/prepare_debian_package.sh
Provide a flexibility to choose path where deb packet will install
it's content.
Can be useful to put less mess into /usr/bin
> Allow alternative paths for deb packet generator

- Antlr/Comments.cs
Problems starts, when ASN.1 or ACN files requires some additional license comments at beginning of file. Now some special comments "--!" will no longer be gathered for types.
> Comments starting with --! will be ignored during ICD generation

- Backend2.ST/icd_acn.stg
When comment was present, its row had too big colspan, breaking table
display in some browsers.
> ICD ACN: fixed layout of "SEQUENCE OF/STRING" tables

- Backend.c.ST/c_aux.stg
memory.h is not a standard C header (and is not present on some
compilers distributions), string.h will be included instead
> Removed non-standard header from autogenerated C test cases

- asn1crt/ber.c
static analysis tool (scan-build) reported that for BerTag == 0 method
BerDecodeTag might act in undefined way (shift by negative number of
bits).
BER tag zero is reserved and should not be used. Yet I assumed
BerDecodeTag should still be able to read it.
> asn1crt - fixed undefined behavior when using some BER tags

- Backend.c.ST/c_acn.stg
- Backend.c.ST/c_aux.stg
static code analysis revealed that `ret = TRUE;` assignments are not
necessary, as `ret` is usually initialized to `TRUE` on its declaration
and then assigned `FALSE` on error.
This commits ensures all `flag ret` declarations also define it value
and removed `ret = TRUE` assignments.
> C ACN generator - removed dead assignments

- Asn1f2/Program.cs
- Backend.c.ST/c_aux.stg
- Backend.c/automatic_test_cases.fs
I've changed a little bit generated C auto cases, to allow users to provide custom output formatter (I was able to produce required XML in xUnit style output and integrate with reporting system). Default output formatter produces exactly same results as original.
This change also allows users to run tests without using `main` function generated by `asn1scc`. Might be useful for running tests in some embedded environments.
> Custom output of unit tests

- Backend.c.ST/c_aux.stg
Really small fix, removes clang warning in generated code
> fixed missing new line in generated C headers

- asn1crt/real.c
it's an ancient compiler, but used in RTEMS 4.8.x
> asn1crt: fixed strict-aliasing related warning on gcc 4.2.4

- Asn1f2/Asn1f2.csproj
Duplicated items in ItemGroup causes Microsoft's msbuild to fail.
> fixed compilation after using wildcards in csproj files

- FrontEndAst/MapParamAstToNonParamAst.fs
- FrontEndAst/RemoveParamterizedTypes.fs
This closes #115
Also - I've removed some code duplication - in `MapParamAstToNonParamAst.fs` imported modules have already been filtered for parametrized types.
> [V4] ImportedModules will appear in XML AST even when only values are imported

- Asn1f4/Program.fs
- CommonTypes/CommonTypes.fs
- FrontEndAst/FrontEntMain.fs
- Service.Implementation/Asn1Service.fs
Streams instead of file names in core functions. Service no longer needs to create temporary input files.
Outputs not yet refactored.
> [V4] Input files abstraction

- Antlr/ErrorFormatter.cs
- Tests/scripts/runTests.py
- v4Tests/scripts/runTests.py
Path should be reported as it was passed to the generator (simplifies reading error messages).
Marked as WIP as still needs some polishing in tests
> [V4] Complete file location in error messages

- asn1crt/xer.c
Attempt to match the rules:
> 9.2.1 The real value zero shall be encoded as "0".
> 9.2.2 For all other values, the following subclauses specify restrictions that apply to "realnumber" (see ITU-T Rec. X.680 | ISO/IEC 8824-1, 11.9).
> 9.2.3 The "realnumber" shall be normalized so that the integer part consists of a single, non-zero digit. The decimal point shall be present and shall be followed by a fractional part containing at least one digit (which may be zero). The fractional part shall not contain any trailing zeros after the first digit.
> 9.2.4 The fractional part shall be followed by an "E" (not an "e") and by an exponent (which may be zero).
> NOTE – Leading zeros in the exponent are already forbidden by ITU-T Rec. X.680 | ISO/IEC 8824-1, 11.9.
> 9.2.5 No "+" sign shall be present …
> XER encoding rules for real values

- Dockerfile
- Dockerfile.runtime
- README.md
- asn1-docker.sh
The modifications (only on Dockerfile. there's a shell script to call the build docker image for convenience) allows the use of the build docker image, as if ASN1SCC is installed on the host. This makes sure that the dependencies of the ASN1SCC is self contained in the docker image and does not interfere with or is affected from the host environment and will generate the same on all platforms.
> docker image now can be called as executable

- asn1crt/asn1crt_encoding.h
In f3f7fae201f9 ("support for OCTET STRING (CONTAINING Other-Type)"),
BitStream_EncodeOctetString_fragmentation() and
BitStream_DecodeOctetString_fragmentation() were added, but no
prototypes were added.
When compiling the generated ASN.1 encoders and decoders with g++, the
following error is reported:
"""
error: no previous declaration for ‘flag BitStream_EncodeOctetString_fragmentation(i3ds_asn1::BitStream*, const byte*, int)’
[-Werror=missing-declarations]
flag BitStream_EncodeOctetString_fragmentation(BitStream* pBitStrm, const byte* arr, int nCount) {
compilation terminated due to -Wfatal-errors.
"""
> asn1crt: add missing prototypes for (De|En)codeOctetString_fragmentation

- asn1crt/asn1crt.h
__STDC_VERSION__ is not mandatory for g++ to define, and when compiling
the generated code with -Werror=undef this yields
error: "__STDC_VERSION__" is not defined, evaluates to 0
C++ has built-in support for bool, so make sure this is only defined
when __cplusplus is not set. Use cstdint for uintXX_t values.
> Be careful when referencing defines and do not redeclare built-ins (C++)

- Docs/examples/streaming_mode/c_out/Makefile
- asn1crt/asn1crt_encoding.c
- asn1crt/asn1crt_encoding.h
- asn1crt/asn1crt_encoding_acn.c
ASN1SCC defines a `--streaming-mode` flag and a (nearly undocumented) streaming API, but the streaming API is not usable. `fetchData` and `pushData` are always defined as no-op functions, and there is no way to redefine them. It looks like this was a simple oversight, possibly caused by leftover debug code. This is my attempt to fix it, as well as to correct a few typos (`bitstrean`->`bitstream`) and remove some trailing whitespace.
These changes were enough to make the C test cases in `Docs/examples/streaming-mode` pass (on Linux, after changing `rsize_t` to `size_t`).
Because I do not know .NET or F#, I have not made any changes to the F# code; all changes are in C files. This means that `--streaming-mode` still does not change `asn1crt_encoding.{c, h}`. Instead, I added an …
> Fix C streaming mode

- README.md
Hello! Not sure if documentation is outdated to refer to v6.0 or whether I am missing something. I was able to successfully compile asn1scc from source with .NET 7.0 sdk and I noticed there was a [release a while ago](https://github.com/ttsiodras/asn1scc/releases/tag/4.5.0.0) for .NET 7.0 support
> Update README to link to .NET 7.0 version

- BackendAst/DAstACN.fs
- BackendAst/DAstConstruction.fs
- BackendAst/DAstEqual.fs
- BackendAst/DAstInitialize.fs
- BackendAst/DAstUPer.fs
- BackendAst/DastTestCaseCreation.fs
- BackendAst/DastValidate2.fs
- BackendAst/GenerateFiles.fs
- CommonTypes/CommonTypes.fs
- FrontEndAst/AcnCreateFromAntlr.fs
- FrontEndAst/Asn1AcnAst.fs
- FrontEndAst/DAst.fs
- FrontEndAst/LspAst.fs
- asn1scc/Program.fs
This PR introduces functionality to **automatically detect and exclude unused generated functions**, resulting in significantly **smaller output code** for both C and Ada backends.
1. **Unused Function Elimination via `-icdPdus`**  
When using the `-icdPdus` argument, ASN1SCC now performs a dependency analysis starting from the specified PDUs and their associated functions (`isEqual()`, `isValid()`, `init()`, `encode()`, and `decode()`).
- Only the functions directly or indirectly required by these PDUs are generated.
- All unused functions are excluded from the output, reducing code size and improving maintainability.
2. **New `-dpdus` Argument**  
A new command-line option, `-dpdus`, was added to help identify Protocol Data Units (PDUs) in the input ASN.1 grammar.
- PDUs are defined as …
> Optimize Code Generation by eliminating Unused Functions
